import type { AppData, ContentItem, Material, Product, Task } from "./types";
import { EMPTY_CHECKLIST } from "./types";

const checklist = (partial: Partial<typeof EMPTY_CHECKLIST> = {}) => ({
  ...EMPTY_CHECKLIST,
  ...partial,
});

export const MATERIALS: Material[] = [
  {
    id: "m-natural-cotton",
    name: "Natural Cotton Yarn",
    type: "yarn",
    supplier: "Island Fibre Co.",
    supplierLocation: "Bridgetown, Barbados",
    variant: "Undyed cream, DK, 100g",
    purchaseUnit: "skein",
    quantityPurchased: 12,
    quantityOnHand: 3,
    purchaseCost: 132,
    shipping: 12,
    duties: 6,
    usableUnits: 12,
    reorderLevel: 4,
    lastPurchased: "2026-08-02",
    notes: "Workhorse yarn for totes and holders. Softens beautifully after a cool wash.",
    imageUrl: "/materials/natural-cotton.jpg",
  },
  {
    id: "m-purple-cotton",
    name: "Purple Cotton Yarn",
    type: "yarn",
    supplier: "Island Fibre Co.",
    supplierLocation: "Bridgetown, Barbados",
    variant: "Deep violet, DK, 100g",
    purchaseUnit: "skein",
    quantityPurchased: 10,
    quantityOnHand: 7,
    purchaseCost: 108,
    shipping: 8,
    duties: 2,
    usableUnits: 10,
    reorderLevel: 3,
    lastPurchased: "2026-08-02",
    notes: "The bottle-holder colour. Photograph in shade — it reads richer than in noon sun.",
    imageUrl: "/materials/purple-cotton.jpg",
  },
  {
    id: "m-brass-drings",
    name: "Brass D-rings",
    type: "hardware",
    supplier: "Harbour Findings",
    supplierLocation: "Port of Spain",
    variant: "25mm, unlacquered brass",
    purchaseUnit: "unit",
    quantityPurchased: 40,
    quantityOnHand: 24,
    purchaseCost: 48,
    shipping: 8,
    duties: 2,
    usableUnits: 40,
    reorderLevel: 12,
    lastPurchased: "2026-07-18",
    notes: "Will patina. A feature, not a flaw.",
  },
  {
    id: "m-kraft-tags",
    name: "Kraft Hang Tags",
    type: "packaging",
    supplier: "Press & Grain",
    supplierLocation: "Speightstown",
    variant: "Letterpress, hummingbird mark",
    purchaseUnit: "unit",
    quantityPurchased: 50,
    quantityOnHand: 18,
    purchaseCost: 32,
    shipping: 8.5,
    duties: 2,
    usableUnits: 50,
    reorderLevel: 20,
    lastPurchased: "2026-08-07",
    notes: "Tied with waxed linen. Reorder before the next market.",
  },
  {
    id: "m-dust-bags",
    name: "Reusable Dust Bags",
    type: "packaging",
    supplier: "Soft Goods Atelier",
    supplierLocation: "Castries",
    variant: "Unbleached cotton, drawstring",
    purchaseUnit: "unit",
    quantityPurchased: 20,
    quantityOnHand: 14,
    purchaseCost: 36,
    shipping: 6.4,
    duties: 1.6,
    usableUnits: 20,
    reorderLevel: 10,
    lastPurchased: "2026-08-07",
    notes: "Customers keep these. Worth the cost.",
  },
  {
    id: "m-seafoam-cotton",
    name: "Seafoam Cotton Yarn",
    type: "yarn",
    supplier: "Island Fibre Co.",
    supplierLocation: "Bridgetown, Barbados",
    variant: "Sea-glass green, DK, 100g",
    purchaseUnit: "skein",
    quantityPurchased: 8,
    quantityOnHand: 5,
    purchaseCost: 88,
    shipping: 6.4,
    duties: 1.6,
    usableUnits: 8,
    reorderLevel: 3,
    lastPurchased: "2026-07-22",
    notes: "Reads as water in photographs. Pair with natural.",
  },
  {
    id: "m-coral-cotton",
    name: "Coral Cotton Yarn",
    type: "yarn",
    supplier: "Island Fibre Co.",
    supplierLocation: "Bridgetown, Barbados",
    variant: "Muted clay, DK, 100g",
    purchaseUnit: "skein",
    quantityPurchased: 6,
    quantityOnHand: 4,
    purchaseCost: 66,
    shipping: 5.4,
    duties: 1.8,
    usableUnits: 6,
    reorderLevel: 2,
    lastPurchased: "2026-07-22",
    notes: "Use sparingly — it is the accent, not the field.",
  },
  {
    id: "m-linen-blend",
    name: "Natural Linen Blend",
    type: "yarn",
    supplier: "Atlantic Mill Ends",
    supplierLocation: "Lisbon via Bridgetown",
    variant: "Linen/cotton, aran, 100g",
    purchaseUnit: "skein",
    quantityPurchased: 8,
    quantityOnHand: 4,
    purchaseCost: 104,
    shipping: 10,
    duties: 2,
    usableUnits: 8,
    reorderLevel: 2,
    lastPurchased: "2026-07-11",
    notes: "Structure for market totes. Blooms after blocking.",
  },
  {
    id: "m-indigo-cotton",
    name: "Indigo Cotton Yarn",
    type: "yarn",
    supplier: "Island Fibre Co.",
    supplierLocation: "Bridgetown, Barbados",
    variant: "Deep indigo, DK, 100g",
    purchaseUnit: "skein",
    quantityPurchased: 4,
    quantityOnHand: 2,
    purchaseCost: 48,
    shipping: 3.2,
    duties: 0.8,
    usableUnits: 4,
    reorderLevel: 2,
    lastPurchased: "2026-06-30",
    notes: "May crock slightly when new. Rinse before making.",
  },
  {
    id: "m-snaps",
    name: "Magnetic Snaps",
    type: "hardware",
    supplier: "Harbour Findings",
    supplierLocation: "Port of Spain",
    variant: "18mm, antique brass",
    purchaseUnit: "unit",
    quantityPurchased: 24,
    quantityOnHand: 12,
    purchaseCost: 42,
    shipping: 6.8,
    duties: 1.6,
    usableUnits: 24,
    reorderLevel: 8,
    lastPurchased: "2026-07-18",
    notes: "",
  },
  {
    id: "m-leather-handles",
    name: "Leather Handles",
    type: "hardware",
    supplier: "Shore Hide",
    supplierLocation: "Oistins",
    variant: "Vegetable tan, 60cm pair",
    purchaseUnit: "pair",
    quantityPurchased: 10,
    quantityOnHand: 4,
    purchaseCost: 72,
    shipping: 10,
    duties: 3,
    usableUnits: 10,
    reorderLevel: 3,
    lastPurchased: "2026-07-04",
    notes: "Darken with handling. Do not oil before first sale.",
  },
  {
    id: "m-cotton-cord",
    name: "Cotton Cord",
    type: "hardware",
    supplier: "Island Fibre Co.",
    supplierLocation: "Bridgetown, Barbados",
    variant: "4mm, natural",
    purchaseUnit: "metre",
    quantityPurchased: 30,
    quantityOnHand: 10,
    purchaseCost: 42,
    shipping: 9,
    duties: 3,
    usableUnits: 30,
    reorderLevel: 8,
    lastPurchased: "2026-06-20",
    notes: "",
  },
  {
    id: "m-tissue",
    name: "Tissue Paper",
    type: "packaging",
    supplier: "Press & Grain",
    supplierLocation: "Speightstown",
    variant: "Ivory, acid-free",
    purchaseUnit: "sheet",
    quantityPurchased: 80,
    quantityOnHand: 30,
    purchaseCost: 22,
    shipping: 4.4,
    duties: 1.6,
    usableUnits: 80,
    reorderLevel: 20,
    lastPurchased: "2026-08-07",
    notes: "",
  },
  {
    id: "m-twill-tape",
    name: "Cotton Twill Tape",
    type: "hardware",
    supplier: "Soft Goods Atelier",
    supplierLocation: "Castries",
    variant: "15mm, natural",
    purchaseUnit: "metre",
    quantityPurchased: 25,
    quantityOnHand: 15,
    purchaseCost: 16,
    shipping: 5.5,
    duties: 1,
    usableUnits: 25,
    reorderLevel: 8,
    lastPurchased: "2026-06-20",
    notes: "",
  },
  {
    id: "m-hook-5mm",
    name: "Crochet Hook 5mm",
    type: "tools",
    supplier: "Studio Cupboard",
    supplierLocation: "Home studio",
    variant: "Birch, inline",
    purchaseUnit: "unit",
    quantityPurchased: 3,
    quantityOnHand: 2,
    purchaseCost: 18,
    shipping: 1.5,
    duties: 0,
    usableUnits: 3,
    reorderLevel: 1,
    lastPurchased: "2026-05-12",
    notes: "Not for sale. Track so replacements are ordered before a market week.",
  },
  {
    id: "m-blocking-mats",
    name: "Blocking Mats",
    type: "tools",
    supplier: "Studio Cupboard",
    supplierLocation: "Home studio",
    variant: "Puzzle set, 9 tiles",
    purchaseUnit: "set",
    quantityPurchased: 1,
    quantityOnHand: 1,
    purchaseCost: 28,
    shipping: 5.8,
    duties: 0,
    usableUnits: 1,
    reorderLevel: 0,
    lastPurchased: "2026-03-02",
    notes: "Keep out of noon sun — they warp.",
  },
  {
    id: "m-care-cards",
    name: "Care Cards",
    type: "packaging",
    supplier: "Press & Grain",
    supplierLocation: "Speightstown",
    variant: "Letterpress, cotton care",
    purchaseUnit: "unit",
    quantityPurchased: 50,
    quantityOnHand: 25,
    purchaseCost: 16,
    shipping: 3.2,
    duties: 0.8,
    usableUnits: 50,
    reorderLevel: 15,
    lastPurchased: "2026-08-07",
    notes: "",
  },
  {
    id: "m-waxed-linen",
    name: "Waxed Linen Thread",
    type: "hardware",
    supplier: "Harbour Findings",
    supplierLocation: "Port of Spain",
    variant: "Natural, 50m spool",
    purchaseUnit: "spool",
    quantityPurchased: 4,
    quantityOnHand: 3,
    purchaseCost: 16.4,
    shipping: 2.4,
    duties: 0.4,
    usableUnits: 4,
    reorderLevel: 1,
    lastPurchased: "2026-07-18",
    notes: "For tags and handle wrapping.",
  },
];

export const PRODUCTS: Product[] = [
  {
    id: "p-purple-holder",
    name: "Purple Water Bottle Holder",
    category: "Accessories",
    status: "in-production",
    description:
      "A close-fit cotton holder for moving through the island with a bottle at your hip. Deep violet, brass D-ring, meant to be used hard.",
    imageUrl: "/products/purple-holder.jpg",
    swatch: "#5C3A7A",
    quantityMade: 0,
    quantityAvailable: 0,
    sellingPrice: 48,
    wholesalePrice: 28,
    targetMargin: 0.65,
    packagingCost: 1.12,
    otherDirectCosts: 0,
    hoursWorked: 0.4,
    labourRate: 5,
    startDate: "2026-08-22",
    targetCompletionDate: "2026-08-29",
    productionNotes: "Last round of the mesh body. Attach D-ring and weave in ends this morning.",
    contentChecklist: checklist({ makingVideo: true }),
    materials: [
      { materialId: "m-purple-cotton", quantity: 0.85 },
      { materialId: "m-brass-drings", quantity: 2 },
      { materialId: "m-kraft-tags", quantity: 1 },
    ],
    stockDeducted: false,
    timerRunning: false,
  },
  {
    id: "p-tide-tote",
    name: "Tide Tote",
    category: "Bags",
    status: "finished",
    description:
      "A generous market tote in natural and seafoam cotton. Leather handles, magnetic snap, room for a week's fruit.",
    imageUrl: "/products/tide-tote.jpg",
    swatch: "#7FA392",
    quantityMade: 2,
    quantityAvailable: 1,
    sellingPrice: 145,
    wholesalePrice: 85,
    targetMargin: 0.64,
    packagingCost: 0.65,
    otherDirectCosts: 0,
    hoursWorked: 0.2,
    labourRate: 5,
    startDate: "2026-07-28",
    targetCompletionDate: "2026-08-12",
    productionNotes: "Blocked and tagged. Needs photography before listing.",
    contentChecklist: checklist({ productDescription: true }),
    materials: [
      { materialId: "m-natural-cotton", quantity: 2.2 },
      { materialId: "m-seafoam-cotton", quantity: 0.8 },
      { materialId: "m-leather-handles", quantity: 1 },
      { materialId: "m-snaps", quantity: 1 },
      { materialId: "m-dust-bags", quantity: 1 },
      { materialId: "m-kraft-tags", quantity: 1 },
    ],
    frozenTrueCost: 52.4,
    stockDeducted: true,
    timerRunning: false,
  },
  {
    id: "p-island-market",
    name: "Island Market Tote",
    category: "Bags",
    status: "prototype",
    description:
      "A structured tote in linen blend for Saturday market runs. Firmer body than the Tide Tote, with a quieter colour story.",
    imageUrl: "/products/island-market-tote.jpg",
    swatch: "#D9C7A8",
    quantityMade: 1,
    quantityAvailable: 0,
    sellingPrice: 165,
    wholesalePrice: 95,
    targetMargin: 0.63,
    packagingCost: 0.75,
    otherDirectCosts: 0,
    hoursWorked: 0,
    labourRate: 5,
    startDate: "2026-08-08",
    targetCompletionDate: "2026-09-04",
    productionNotes: "Prototype in hand. Customer already waiting on the first finished piece.",
    contentChecklist: checklist({ productPhoto: true, lifestyleShot: true }),
    materials: [
      { materialId: "m-linen-blend", quantity: 2 },
      { materialId: "m-natural-cotton", quantity: 1.2 },
      { materialId: "m-leather-handles", quantity: 1 },
      { materialId: "m-brass-drings", quantity: 2 },
      { materialId: "m-dust-bags", quantity: 1 },
      { materialId: "m-kraft-tags", quantity: 1 },
      { materialId: "m-twill-tape", quantity: 2 },
    ],
    stockDeducted: false,
    timerRunning: false,
  },
  {
    id: "p-wine-holder",
    name: "Wine Bottle Holder",
    category: "Accessories",
    status: "selling",
    description:
      "A gift-ready holder for a bottle of wine. Plum and natural cotton, brass ring, meant for a table or a walk to dinner.",
    imageUrl: "/products/wine-holder.jpg",
    swatch: "#6B3A4A",
    quantityMade: 14,
    quantityAvailable: 4,
    sellingPrice: 42,
    wholesalePrice: 24,
    targetMargin: 0.65,
    packagingCost: 0.9,
    otherDirectCosts: 0,
    hoursWorked: 0.3,
    labourRate: 5,
    startDate: "2026-06-02",
    productionNotes: "Steady seller at Sunday market.",
    contentChecklist: checklist({
      productPhoto: true,
      detailShot: true,
      productDescription: true,
      listingReady: true,
      story: true,
    }),
    materials: [
      { materialId: "m-purple-cotton", quantity: 0.4 },
      { materialId: "m-natural-cotton", quantity: 0.4 },
      { materialId: "m-brass-drings", quantity: 1 },
      { materialId: "m-kraft-tags", quantity: 1 },
    ],
    frozenTrueCost: 14.5,
    stockDeducted: true,
    timerRunning: false,
  },
  {
    id: "p-seafoam-clutch",
    name: "Seafoam Clutch",
    category: "Bags",
    status: "finished",
    description: "An envelope clutch in sea-glass cotton. Evening, market, or a notebook.",
    imageUrl: "/products/seafoam-clutch.jpg",
    swatch: "#6FA394",
    quantityMade: 3,
    quantityAvailable: 2,
    sellingPrice: 78,
    targetMargin: 0.64,
    packagingCost: 1.1,
    otherDirectCosts: 0,
    hoursWorked: 0.5,
    labourRate: 5,
    contentChecklist: checklist({ productPhoto: true, productDescription: true }),
    materials: [
      { materialId: "m-seafoam-cotton", quantity: 1.1 },
      { materialId: "m-snaps", quantity: 1 },
      { materialId: "m-kraft-tags", quantity: 1 },
      { materialId: "m-dust-bags", quantity: 1 },
    ],
    frozenTrueCost: 28,
    stockDeducted: true,
    timerRunning: false,
    productionNotes: "",
  },
  {
    id: "p-coral-pouch",
    name: "Coral Market Pouch",
    category: "Accessories",
    status: "finished",
    description: "A small pouch for coins, keys, and a lipstick. Muted clay cotton.",
    imageUrl: "/products/coral-pouch.jpg",
    swatch: "#C26A56",
    quantityMade: 5,
    quantityAvailable: 3,
    sellingPrice: 55,
    targetMargin: 0.64,
    packagingCost: 0.8,
    otherDirectCosts: 0,
    hoursWorked: 0.35,
    labourRate: 5,
    contentChecklist: checklist({ productPhoto: true }),
    materials: [
      { materialId: "m-coral-cotton", quantity: 0.7 },
      { materialId: "m-cotton-cord", quantity: 0.8 },
      { materialId: "m-kraft-tags", quantity: 1 },
    ],
    frozenTrueCost: 19,
    stockDeducted: true,
    timerRunning: false,
    productionNotes: "",
  },
  {
    id: "p-driftwood",
    name: "Driftwood Crossbody",
    category: "Bags",
    status: "selling",
    description: "A hands-free bag in driftwood beige. Long strap, quiet hardware.",
    imageUrl: "/products/driftwood-crossbody.jpg",
    swatch: "#C4B49A",
    quantityMade: 3,
    quantityAvailable: 1,
    sellingPrice: 128,
    targetMargin: 0.63,
    packagingCost: 1.2,
    otherDirectCosts: 0,
    hoursWorked: 0.6,
    labourRate: 5,
    contentChecklist: checklist({
      productPhoto: true,
      detailShot: true,
      lifestyleShot: true,
      productDescription: true,
      listingReady: true,
    }),
    materials: [
      { materialId: "m-natural-cotton", quantity: 1.6 },
      { materialId: "m-linen-blend", quantity: 0.8 },
      { materialId: "m-cotton-cord", quantity: 1.2 },
      { materialId: "m-snaps", quantity: 1 },
      { materialId: "m-dust-bags", quantity: 1 },
    ],
    frozenTrueCost: 46,
    stockDeducted: true,
    timerRunning: false,
    productionNotes: "",
  },
  {
    id: "p-sunrise-sling",
    name: "Sunrise Bottle Sling",
    category: "Accessories",
    status: "finished",
    description: "A peach and natural bottle sling for morning walks.",
    imageUrl: "/products/sunrise-sling.jpg",
    swatch: "#E0A07A",
    quantityMade: 4,
    quantityAvailable: 2,
    sellingPrice: 48,
    targetMargin: 0.65,
    packagingCost: 1.12,
    otherDirectCosts: 0,
    hoursWorked: 0.4,
    labourRate: 5,
    contentChecklist: checklist({ productPhoto: true, detailShot: true }),
    materials: [
      { materialId: "m-coral-cotton", quantity: 0.5 },
      { materialId: "m-natural-cotton", quantity: 0.4 },
      { materialId: "m-brass-drings", quantity: 2 },
      { materialId: "m-kraft-tags", quantity: 1 },
    ],
    frozenTrueCost: 16.5,
    stockDeducted: true,
    timerRunning: false,
    productionNotes: "",
  },
  {
    id: "p-harbour-shopper",
    name: "Harbour Shopper",
    category: "Bags",
    status: "idea",
    description: "A fold-flat shopper for the fish market. Indigo and natural. Still a sketch.",
    swatch: "#3D4F6F",
    quantityMade: 0,
    quantityAvailable: 0,
    sellingPrice: 135,
    targetMargin: 0.64,
    packagingCost: 1,
    otherDirectCosts: 0,
    hoursWorked: 0,
    labourRate: 5,
    contentChecklist: checklist(),
    materials: [
      { materialId: "m-indigo-cotton", quantity: 2 },
      { materialId: "m-natural-cotton", quantity: 1 },
    ],
    stockDeducted: false,
    timerRunning: false,
    productionNotes: "",
  },
  {
    id: "p-night-bloom",
    name: "Night Bloom Wrap",
    category: "Accessories",
    status: "in-production",
    description: "A light evening wrap in indigo and seafoam. Slow work, for September.",
    swatch: "#2C3A55",
    quantityMade: 0,
    quantityAvailable: 0,
    sellingPrice: 185,
    targetMargin: 0.62,
    packagingCost: 1.4,
    otherDirectCosts: 0,
    hoursWorked: 2.5,
    labourRate: 5,
    startDate: "2026-08-18",
    targetCompletionDate: "2026-09-12",
    productionNotes: "Body in progress. Do not rush — this is the September story piece.",
    contentChecklist: checklist({ makingVideo: true }),
    materials: [
      { materialId: "m-indigo-cotton", quantity: 1.5 },
      { materialId: "m-seafoam-cotton", quantity: 1.2 },
    ],
    stockDeducted: false,
    timerRunning: false,
  },
  {
    id: "p-salt-air",
    name: "Salt Air Scarf",
    category: "Accessories",
    status: "archived",
    description: "An earlier scarf experiment. Retired from the active line; pattern notes kept.",
    swatch: "#B7C4C0",
    quantityMade: 2,
    quantityAvailable: 0,
    sellingPrice: 95,
    targetMargin: 0.6,
    packagingCost: 0.6,
    otherDirectCosts: 0,
    hoursWorked: 1.2,
    labourRate: 5,
    contentChecklist: checklist({ productPhoto: true }),
    materials: [{ materialId: "m-natural-cotton", quantity: 2 }],
    frozenTrueCost: 32,
    stockDeducted: true,
    timerRunning: false,
    productionNotes: "Archived after two made. Too close to the wrap.",
  },
];

const shot = (...items: string[]) => items;

export const CONTENT: ContentItem[] = [
  {
    id: "c-market-morning",
    title: "Market Morning Reel",
    pillar: "Island living",
    format: "reel",
    status: "ready",
    linkedProductId: "p-island-market",
    coreMessage: "The tote is made for the same morning the island already lives.",
    hook: "Before the fruit is gone, the bag is already on your shoulder.",
    caption:
      "Saturday starts at the stall. The Island Market Tote was made for mangoes, limes, and the walk home in the heat. Would you carry this colour into your day?",
    cta: "Would you carry this colour into your day?",
    shotList: shot(
      "Hands lifting the tote off a wooden stall",
      "Fruit settling into the body of the bag",
      "Walking away, strap on shoulder, sea in the distance",
    ),
    assets: [
      { label: "Cut footage", done: true },
      { label: "Caption", done: true },
      { label: "Cover frame", done: true },
    ],
    targetDate: "2026-08-29",
    channel: "Instagram",
  },
  {
    id: "c-tide-sun",
    title: "Tide Tote in the Sun",
    pillar: "Products",
    format: "carousel",
    status: "captured",
    linkedProductId: "p-tide-tote",
    coreMessage: "The Tide Tote belongs in daylight, not on a white sweep.",
    hook: "It looks like the water it was named for.",
    caption: "Natural cotton, seafoam, leather that will darken. Photographed where it will actually live.",
    cta: "Save this for your next market morning.",
    shotList: shot("Tote on sand", "Handle detail", "Interior snap", "Worn on the shoulder"),
    assets: [
      { label: "Raw photos", done: true },
      { label: "Selects", done: false },
      { label: "Caption", done: false },
    ],
    targetDate: "2026-08-31",
  },
  {
    id: "c-yarn-to-carry",
    title: "From Yarn to Carry-on",
    pillar: "Making",
    format: "reel",
    status: "idea",
    linkedProductId: "p-purple-holder",
    coreMessage: "A skein of purple cotton becomes a bottle holder made for moving through the island.",
    hook: "From a skein of purple cotton to a bottle holder made for moving through the island.",
    caption: "",
    cta: "Would you carry this colour into your day?",
    shotList: shot(
      "Yarn texture",
      "Hands making",
      "Hardware detail",
      "Finished product in use",
      "Coastal location reveal",
    ),
    assets: [
      { label: "Making clip", done: false },
      { label: "Finished clip", done: false },
    ],
  },
  {
    id: "c-cotton-matters",
    title: "Why Cotton Matters Here",
    pillar: "Fibre and yarn education",
    format: "carousel",
    status: "editing",
    linkedMaterialId: "m-natural-cotton",
    coreMessage: "Cotton is not a trend here. It is what the climate asks for.",
    hook: "Why this fibre, on this island.",
    caption:
      "Cotton breathes in August. It softens with salt air. It is the honest choice for bags that will be used, not stored.",
    cta: "What fibre do you reach for in the heat?",
    shotList: shot("Skein close-up", "Hands winding", "Finished tote in sun", "Wash care card"),
    assets: [
      { label: "Slides drafted", done: true },
      { label: "Type set", done: false },
    ],
    targetDate: "2026-09-02",
  },
  {
    id: "c-hummingbird-mark",
    title: "The Hummingbird on the Tag",
    pillar: "Hummingbird / brand world",
    format: "story",
    status: "idea",
    coreMessage: "The mark is a line, not a mascot. It is the pause between making and selling.",
    hook: "A small bird, a small tag, a whole studio.",
    caption: "",
    cta: "Look for it on the next piece you pick up.",
    shotList: shot("Letterpress tag", "Waxed linen knot", "Tag on a finished bag"),
    assets: [{ label: "Tag photo", done: false }],
  },
  {
    id: "c-porch-light",
    title: "Porch Light Making",
    pillar: "Founder story",
    format: "reel",
    status: "idea",
    coreMessage: "Most of the work happens after the heat drops.",
    hook: "The studio is a porch and a lamp.",
    caption: "",
    cta: "This is where the Tide Tote was finished.",
    shotList: shot("Hands in lamplight", "Hook and yarn", "Night insects, quiet"),
    assets: [{ label: "Clip", done: false }],
  },
  {
    id: "c-sea-grape",
    title: "Sea Grape Hour",
    pillar: "Nature",
    format: "photo",
    status: "captured",
    coreMessage: "Colour notes from the coast, not from a trend deck.",
    hook: "The palette is already outside.",
    caption: "Sea grape, wet sand, the inside of a conch. This is how seafoam got into the tote.",
    cta: "Save for colour notes.",
    shotList: shot("Sea grape leaves", "Wet sand", "Yarn beside the leaf"),
    assets: [
      { label: "Photos", done: true },
      { label: "Selects", done: true },
    ],
  },
  {
    id: "c-wine-gift",
    title: "Take a Bottle, Beautifully",
    pillar: "Products",
    format: "carousel",
    status: "ready",
    linkedProductId: "p-wine-holder",
    coreMessage: "The wine holder is the easiest gift in the line.",
    hook: "Do not wrap the bottle. Carry it.",
    caption:
      "The Wine Bottle Holder is ready now — plum, natural, a brass ring. A gift that does not look like it came from a shop.",
    cta: "Message to reserve one for this weekend.",
    shotList: shot("Holder on table", "Bottle sliding in", "Walking out the door"),
    assets: [
      { label: "Photos", done: true },
      { label: "Caption", done: true },
    ],
    targetDate: "2026-08-29",
    channel: "Instagram",
  },
  {
    id: "c-listing-tide",
    title: "Tide Tote listing copy",
    pillar: "Products",
    format: "product-listing",
    status: "idea",
    linkedProductId: "p-tide-tote",
    coreMessage: "Need photography before this can go live.",
    hook: "A tote named for the water it faces.",
    caption: "",
    cta: "Available this week.",
    shotList: shot("Hero", "Detail", "In use", "Scale"),
    assets: [{ label: "Copy draft", done: false }],
  },
  {
    id: "c-sunday-table",
    title: "Sunday Table",
    pillar: "Island living",
    format: "photo",
    status: "published",
    publishedDate: "2026-08-03",
    channel: "Instagram",
    coreMessage: "The market table is a studio, once a week.",
    hook: "Same cloth, new work.",
    caption: "Sunday at the table. Come say hello.",
    cta: "Find us until noon.",
    shotList: [],
    assets: [],
  },
  {
    id: "c-hands-mesh",
    title: "The Mesh That Holds Water",
    pillar: "Making",
    format: "reel",
    status: "editing",
    linkedProductId: "p-purple-holder",
    coreMessage: "Show the stitch that makes the bottle stay.",
    hook: "It has to hold. That is the whole brief.",
    caption: "",
    cta: "Watch the last round.",
    shotList: shot("Hook entering stitch", "Bottle test", "D-ring attach"),
    assets: [
      { label: "Raw clip", done: true },
      { label: "Cut", done: false },
    ],
  },
  {
    id: "c-founder-why",
    title: "Why I Make Bags, Not Clothes",
    pillar: "Founder story",
    format: "email",
    status: "idea",
    coreMessage: "Bags leave the studio and go into other people's days.",
    hook: "I wanted the work to be used.",
    caption: "",
    cta: "Reply and tell me what you carry.",
    shotList: [],
    assets: [{ label: "Outline", done: false }],
  },
  {
    id: "c-coastal-palette",
    title: "A Palette Taken from the Shore",
    pillar: "Coastal Caribbean life",
    format: "carousel",
    status: "idea",
    coreMessage: "Navy, sand, sea-glass, clay. Not a moodboard — a walk.",
    hook: "These colours were not chosen in software.",
    caption: "",
    cta: "Which one is your weather?",
    shotList: shot("Sand", "Water", "Clay pot", "Yarn"),
    assets: [],
  },
  {
    id: "c-blocking",
    title: "How a Tote Learns Its Shape",
    pillar: "Making",
    format: "photo",
    status: "captured",
    linkedProductId: "p-tide-tote",
    coreMessage: "Blocking is the quiet half of making.",
    hook: "It looks unfinished until it is pinned.",
    caption: "",
    cta: "Save this if you make.",
    shotList: shot("Wet tote", "Pins", "Dry in morning light"),
    assets: [{ label: "Photos", done: true }],
  },
  {
    id: "c-dust-bag",
    title: "The Bag Inside the Bag",
    pillar: "Products",
    format: "story",
    status: "idea",
    linkedMaterialId: "m-dust-bags",
    coreMessage: "Packaging that is kept is not packaging.",
    hook: "You will use this again.",
    caption: "",
    cta: "Swipe for the cotton dust bag.",
    shotList: shot("Dust bag texture", "Tote going in"),
    assets: [],
  },
  {
    id: "c-published-wine",
    title: "Two Wine Holders, One Table",
    pillar: "Products",
    format: "photo",
    status: "published",
    linkedProductId: "p-wine-holder",
    publishedDate: "2026-08-06",
    channel: "Instagram",
    coreMessage: "Social proof from a real dinner.",
    hook: "They left together.",
    caption: "Both sold before noon.",
    cta: "",
    shotList: [],
    assets: [],
  },
  {
    id: "c-published-yarn",
    title: "New Skein, Old Light",
    pillar: "Fibre and yarn education",
    format: "photo",
    status: "published",
    linkedMaterialId: "m-purple-cotton",
    publishedDate: "2026-08-09",
    channel: "Instagram",
    coreMessage: "Introduce the purple before the holder is finished.",
    hook: "This is the colour of the next holder.",
    caption: "Purple cotton, still in the skein.",
    cta: "",
    shotList: [],
    assets: [],
  },
  {
    id: "c-published-walk",
    title: "A Walk with the Crossbody",
    pillar: "Coastal Caribbean life",
    format: "reel",
    status: "published",
    linkedProductId: "p-driftwood",
    publishedDate: "2026-08-14",
    channel: "TikTok",
    coreMessage: "The, not styled.",
    hook: "Hands free for the rest of the day.",
    caption: "Driftwood Crossbody, first wear.",
    cta: "",
    shotList: [],
    assets: [],
  },
  {
    id: "c-published-market",
    title: "Thank you, Sunday",
    pillar: "Island living",
    format: "story",
    status: "published",
    publishedDate: "2026-08-17",
    channel: "Instagram",
    coreMessage: "Close the market day with gratitude, not a hard sell.",
    hook: "Packed up, sunburnt, sold through.",
    caption: "See you next week.",
    cta: "",
    shotList: [],
    assets: [],
  },
  {
    id: "c-clutch-evening",
    title: "Seafoam after Six",
    pillar: "Products",
    format: "photo",
    status: "idea",
    linkedProductId: "p-seafoam-clutch",
    coreMessage: "The clutch is the evening piece in a daytime line.",
    hook: "Not everything is for the market.",
    caption: "",
    cta: "Would you take this out after dark?",
    shotList: shot("Clutch on linen", "Open with a key", "Held in one hand"),
    assets: [],
  },
];

export const TASKS: Task[] = [
  {
    id: "t-finish-purple",
    title: "Finish Purple Water Bottle Holder",
    dueDate: "2026-08-29",
    priority: "high",
    completed: false,
    linkedKind: "product",
    linkedId: "p-purple-holder",
  },
  {
    id: "t-photo-tide",
    title: "Photograph Tide Tote",
    dueDate: "2026-08-29",
    priority: "high",
    completed: false,
    linkedKind: "product",
    linkedId: "p-tide-tote",
  },
  {
    id: "t-post-market",
    title: "Post “Market Morning” Reel",
    dueDate: "2026-08-29",
    priority: "medium",
    completed: false,
    linkedKind: "content",
    linkedId: "c-market-morning",
  },
  {
    id: "t-order-yarn",
    title: "Order natural cotton yarn",
    dueDate: "2026-08-29",
    priority: "high",
    completed: false,
    linkedKind: "material",
    linkedId: "m-natural-cotton",
  },
  {
    id: "t-follow-up",
    title: "Follow up with Island Market customer",
    dueDate: "2026-08-29",
    priority: "high",
    completed: false,
    linkedKind: "order",
    linkedId: "o-island-market",
  },
];

export const SEED: AppData = {
  products: PRODUCTS,
  materials: MATERIALS,
  content: CONTENT,
  tasks: TASKS,
  sales: [
    { id: "s1", date: "2026-08-01", productId: "p-seafoam-clutch", itemName: "Seafoam Clutch", quantity: 1, total: 78, status: "paid" },
    { id: "s2", date: "2026-08-03", productId: "p-wine-holder", itemName: "Wine Bottle Holder", quantity: 2, total: 84, status: "paid" },
    { id: "s3", date: "2026-08-04", productId: "p-wine-holder", itemName: "Wine Bottle Holder", quantity: 2, total: 84, status: "paid" },
    { id: "s4", date: "2026-08-06", productId: "p-sunrise-sling", itemName: "Sunrise Bottle Sling", quantity: 2, total: 96, status: "paid" },
    { id: "s5", date: "2026-08-08", productId: "p-coral-pouch", itemName: "Coral Market Pouch", quantity: 1, total: 55, status: "paid" },
    { id: "s6", date: "2026-08-09", productId: "p-driftwood", itemName: "Driftwood Crossbody", quantity: 1, total: 128, status: "paid" },
    { id: "s7", date: "2026-08-10", productId: "p-tide-tote", itemName: "Tide Tote", quantity: 1, total: 145, status: "paid" },
    { id: "s8", date: "2026-08-11", productId: "p-wine-holder", itemName: "Wine Bottle Holder", quantity: 3, total: 126, status: "paid" },
    { id: "s9", date: "2026-08-13", productId: "p-salt-air", itemName: "Salt Air Scarf", quantity: 1, total: 157, status: "paid" },
    { id: "s10", date: "2026-08-14", productId: "p-tide-tote", itemName: "Tide Tote", quantity: 1, total: 145, status: "paid" },
    { id: "s11", date: "2026-08-16", productId: "p-seafoam-clutch", itemName: "Seafoam Clutch", quantity: 1, total: 78, status: "paid" },
    { id: "s12", date: "2026-08-17", productId: "p-wine-holder", itemName: "Wine Bottle Holder", quantity: 2, total: 84, status: "paid" },
    { id: "s13", date: "2026-08-18", productId: "p-purple-holder", itemName: "Custom Water Bottle Holder", quantity: 2, total: 110, status: "paid", customer: "Walk-in" },
    { id: "s14", date: "2026-08-19", productId: "p-coral-pouch", itemName: "Coral Market Pouch", quantity: 2, total: 110, status: "paid" },
    { id: "s15", date: "2026-08-21", productId: "p-sunrise-sling", itemName: "Sunrise Bottle Sling", quantity: 1, total: 48, status: "paid" },
    { id: "s16", date: "2026-08-23", productId: "p-driftwood", itemName: "Driftwood Crossbody", quantity: 1, total: 128, status: "paid" },
    { id: "s17", date: "2026-08-24", productId: "p-island-market", itemName: "Island Market Tote", quantity: 1, total: 165, status: "awaiting", customer: "Island Market customer" },
    { id: "s18", date: "2026-08-25", productId: "p-wine-holder", itemName: "Wine Bottle Holder", quantity: 2, total: 84, status: "paid" },
    { id: "s19", date: "2026-08-27", productId: "p-seafoam-clutch", itemName: "Seafoam Clutch", quantity: 1, total: 78, status: "paid" },
    { id: "s20", date: "2026-08-28", productId: "p-wine-holder", itemName: "Wine Bottle Holder", quantity: 1, total: 42, status: "paid" },
  ],
  expenses: [
    { id: "e1", date: "2026-08-02", category: "Materials", description: "Purple cotton yarn", amount: 82.6, productRelated: true },
    { id: "e2", date: "2026-08-05", category: "Studio", description: "Studio contribution", amount: 150, productRelated: false },
    { id: "e3", date: "2026-08-07", category: "Packaging", description: "Kraft tags and dust bags", amount: 54, productRelated: true },
    { id: "e4", date: "2026-08-12", category: "Transport", description: "Market and product shoot travel", amount: 48, productRelated: false },
    { id: "e5", date: "2026-08-15", category: "Market fees", description: "Sunday market table", amount: 90, productRelated: false },
    { id: "e6", date: "2026-08-20", category: "Studio", description: "Phone and internet", amount: 45, productRelated: false },
    { id: "e7", date: "2026-08-22", category: "Marketing", description: "Small campaign test", amount: 60, productRelated: false },
    { id: "e8", date: "2026-08-26", category: "Studio", description: "Props and market sundries", amount: 32, productRelated: false },
  ],
  draws: [{ id: "d1", date: "2026-08-20", amount: 200, notes: "August owner draw" }],
  orders: [
    {
      id: "o-purple-batch",
      customerName: "Sunday market hold",
      productId: "p-purple-holder",
      productName: "Purple Water Bottle Holder",
      quantity: 1,
      total: 48,
      status: "open",
      dueDate: "2026-08-29",
      notes: "Finish today so it can be photographed and tabled.",
    },
    {
      id: "o-island-market",
      customerName: "Island Market customer",
      productId: "p-island-market",
      productName: "Island Market Tote",
      quantity: 1,
      total: 165,
      status: "awaiting-payment",
      dueDate: "2026-08-30",
      notes: "Prototype shown; customer asked to collect. Payment still outstanding.",
    },
    {
      id: "o-custom-sling",
      customerName: "Leah M.",
      productId: "p-sunrise-sling",
      productName: "Sunrise Bottle Sling",
      quantity: 1,
      total: 48,
      status: "open",
      dueDate: "2026-09-02",
      notes: "Colour confirmed. Use remaining coral cotton.",
    },
  ],
  commitments: [
    { id: "k1", name: "Sunday market table", amount: 90, date: "2026-08-31", essential: true },
    { id: "k2", name: "Phone and internet", amount: 54, date: "2026-09-03", essential: true },
  ],
  settings: {
    ownerName: "Arlette",
    operatingBuffer: 300,
    openingCash: 141.6,
    currentGoal: "consistency",
    labourRateDefault: 5,
  },
  dismissedMoveIds: [],
  saveError: false,
};

export function cloneSeed(): AppData {
  return structuredClone(SEED);
}
