/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContentRouteImport } from './routes/content'
import { Route as MakeRouteImport } from './routes/make'
import { Route as MoneyRouteImport } from './routes/money'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StockRouteImport } from './routes/stock'
import { Route as ContentContentIdRouteImport } from './routes/content.$contentId'
import { Route as ContentNewRouteImport } from './routes/content.new'
import { Route as MakeProductIdRouteImport } from './routes/make.$productId'
import { Route as MakeNewRouteImport } from './routes/make.new'
import { Route as StockMaterialIdRouteImport } from './routes/stock.$materialId'
import { Route as StockNewRouteImport } from './routes/stock.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const MakeRoute = MakeRouteImport.update({
  id: '/make',
  path: '/make',
  getParentRoute: () => rootRouteImport,
} as any)
const MoneyRoute = MoneyRouteImport.update({
  id: '/money',
  path: '/money',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentContentIdRoute = ContentContentIdRouteImport.update({
  id: '/$contentId',
  path: '/$contentId',
  getParentRoute: () => ContentRoute,
} as any)
const ContentNewRoute = ContentNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ContentRoute,
} as any)
const MakeProductIdRoute = MakeProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => MakeRoute,
} as any)
const MakeNewRoute = MakeNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MakeRoute,
} as any)
const StockMaterialIdRoute = StockMaterialIdRouteImport.update({
  id: '/$materialId',
  path: '/$materialId',
  getParentRoute: () => StockRoute,
} as any)
const StockNewRoute = StockNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => StockRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/content': typeof ContentRouteWithChildren
  '/make': typeof MakeRouteWithChildren
  '/money': typeof MoneyRoute
  '/settings': typeof SettingsRoute
  '/stock': typeof StockRouteWithChildren
  '/content/$contentId': typeof ContentContentIdRoute
  '/content/new': typeof ContentNewRoute
  '/make/$productId': typeof MakeProductIdRoute
  '/make/new': typeof MakeNewRoute
  '/stock/$materialId': typeof StockMaterialIdRoute
  '/stock/new': typeof StockNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/content': typeof ContentRouteWithChildren
  '/make': typeof MakeRouteWithChildren
  '/money': typeof MoneyRoute
  '/settings': typeof SettingsRoute
  '/stock': typeof StockRouteWithChildren
  '/content/$contentId': typeof ContentContentIdRoute
  '/content/new': typeof ContentNewRoute
  '/make/$productId': typeof MakeProductIdRoute
  '/make/new': typeof MakeNewRoute
  '/stock/$materialId': typeof StockMaterialIdRoute
  '/stock/new': typeof StockNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/content': typeof ContentRouteWithChildren
  '/make': typeof MakeRouteWithChildren
  '/money': typeof MoneyRoute
  '/settings': typeof SettingsRoute
  '/stock': typeof StockRouteWithChildren
  '/content/$contentId': typeof ContentContentIdRoute
  '/content/new': typeof ContentNewRoute
  '/make/$productId': typeof MakeProductIdRoute
  '/make/new': typeof MakeNewRoute
  '/stock/$materialId': typeof StockMaterialIdRoute
  '/stock/new': typeof StockNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/content'
    | '/make'
    | '/money'
    | '/settings'
    | '/stock'
    | '/content/$contentId'
    | '/content/new'
    | '/make/$productId'
    | '/make/new'
    | '/stock/$materialId'
    | '/stock/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/content'
    | '/make'
    | '/money'
    | '/settings'
    | '/stock'
    | '/content/$contentId'
    | '/content/new'
    | '/make/$productId'
    | '/make/new'
    | '/stock/$materialId'
    | '/stock/new'
  id:
    | '__root__'
    | '/'
    | '/content'
    | '/make'
    | '/money'
    | '/settings'
    | '/stock'
    | '/content/$contentId'
    | '/content/new'
    | '/make/$productId'
    | '/make/new'
    | '/stock/$materialId'
    | '/stock/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContentRoute: typeof ContentRouteWithChildren
  MakeRoute: typeof MakeRouteWithChildren
  MoneyRoute: typeof MoneyRoute
  SettingsRoute: typeof SettingsRoute
  StockRoute: typeof StockRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/make': {
      id: '/make'
      path: '/make'
      fullPath: '/make'
      preLoaderRoute: typeof MakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/money': {
      id: '/money'
      path: '/money'
      fullPath: '/money'
      preLoaderRoute: typeof MoneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/$contentId': {
      id: '/content/$contentId'
      path: '/$contentId'
      fullPath: '/content/$contentId'
      preLoaderRoute: typeof ContentContentIdRouteImport
      parentRoute: typeof ContentRoute
    }
    '/content/new': {
      id: '/content/new'
      path: '/new'
      fullPath: '/content/new'
      preLoaderRoute: typeof ContentNewRouteImport
      parentRoute: typeof ContentRoute
    }
    '/make/$productId': {
      id: '/make/$productId'
      path: '/$productId'
      fullPath: '/make/$productId'
      preLoaderRoute: typeof MakeProductIdRouteImport
      parentRoute: typeof MakeRoute
    }
    '/make/new': {
      id: '/make/new'
      path: '/new'
      fullPath: '/make/new'
      preLoaderRoute: typeof MakeNewRouteImport
      parentRoute: typeof MakeRoute
    }
    '/stock/$materialId': {
      id: '/stock/$materialId'
      path: '/$materialId'
      fullPath: '/stock/$materialId'
      preLoaderRoute: typeof StockMaterialIdRouteImport
      parentRoute: typeof StockRoute
    }
    '/stock/new': {
      id: '/stock/new'
      path: '/new'
      fullPath: '/stock/new'
      preLoaderRoute: typeof StockNewRouteImport
      parentRoute: typeof StockRoute
    }
  }
}

interface ContentRouteChildren {
  ContentContentIdRoute: typeof ContentContentIdRoute
  ContentNewRoute: typeof ContentNewRoute
}

const ContentRouteChildren: ContentRouteChildren = {
  ContentContentIdRoute: ContentContentIdRoute,
  ContentNewRoute: ContentNewRoute,
}

const ContentRouteWithChildren =
  ContentRoute._addFileChildren(ContentRouteChildren)

interface MakeRouteChildren {
  MakeProductIdRoute: typeof MakeProductIdRoute
  MakeNewRoute: typeof MakeNewRoute
}

const MakeRouteChildren: MakeRouteChildren = {
  MakeProductIdRoute: MakeProductIdRoute,
  MakeNewRoute: MakeNewRoute,
}

const MakeRouteWithChildren = MakeRoute._addFileChildren(MakeRouteChildren)

interface StockRouteChildren {
  StockMaterialIdRoute: typeof StockMaterialIdRoute
  StockNewRoute: typeof StockNewRoute
}

const StockRouteChildren: StockRouteChildren = {
  StockMaterialIdRoute: StockMaterialIdRoute,
  StockNewRoute: StockNewRoute,
}

const StockRouteWithChildren = StockRoute._addFileChildren(StockRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContentRoute: ContentRouteWithChildren,
  MakeRoute: MakeRouteWithChildren,
  MoneyRoute: MoneyRoute,
  SettingsRoute: SettingsRoute,
  StockRoute: StockRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
